import '../../models/wilayah_model.dart';

/// Complete Master Offline Dataset for Kabupaten Sumenep (27 Kecamatan & 283+ Desa/Kelurahan)
class SumenepMasterData {
  static List<DesaModel> get offlineDesaList => _rawSumenepData.asMap().entries.map((entry) {
    return DesaModel(
      id: entry.key + 1,
      kecamatan: entry.value['kec']!,
      desa: entry.value['desa']!,
    );
  }).toList();

  static const List<Map<String, String>> _rawSumenepData = [
    // 1. Kota Sumenep
    {'kec': 'Kota Sumenep', 'desa': 'Bangselok'},
    {'kec': 'Kota Sumenep', 'desa': 'Pajagalan'},
    {'kec': 'Kota Sumenep', 'desa': 'Kepanjin'},
    {'kec': 'Kota Sumenep', 'desa': 'Karangduak'},
    {'kec': 'Kota Sumenep', 'desa': 'Kolor'},
    {'kec': 'Kota Sumenep', 'desa': 'Pabian'},
    {'kec': 'Kota Sumenep', 'desa': 'Marengan Daya'},
    {'kec': 'Kota Sumenep', 'desa': 'Parsanga'},
    {'kec': 'Kota Sumenep', 'desa': 'Pangarangan'},
    {'kec': 'Kota Sumenep', 'desa': 'Pamolokan'},
    {'kec': 'Kota Sumenep', 'desa': 'Kebunan'},
    {'kec': 'Kota Sumenep', 'desa': 'Pandian'},
    {'kec': 'Kota Sumenep', 'desa': 'Paberasan'},
    {'kec': 'Kota Sumenep', 'desa': 'Kacongan'},
    {'kec': 'Kota Sumenep', 'desa': 'Torbang'},

    // 2. Kalianget
    {'kec': 'Kalianget', 'desa': 'Kalianget Timur'},
    {'kec': 'Kalianget', 'desa': 'Kalianget Barat'},
    {'kec': 'Kalianget', 'desa': 'Kalimo\'ok'},
    {'kec': 'Kalianget', 'desa': 'Kertasada'},
    {'kec': 'Kalianget', 'desa': 'Karanganyar'},
    {'kec': 'Kalianget', 'desa': 'Pinggirpapas'},
    {'kec': 'Kalianget', 'desa': 'Mares'},

    // 3. Talango (Kepulauan Poteran)
    {'kec': 'Talango', 'desa': 'Talango'},
    {'kec': 'Talango', 'desa': 'Gapurana'},
    {'kec': 'Talango', 'desa': 'Padike'},
    {'kec': 'Talango', 'desa': 'Cabbiya'},
    {'kec': 'Talango', 'desa': 'Kombang'},
    {'kec': 'Talango', 'desa': 'Palasa'},
    {'kec': 'Talango', 'desa': 'Essang'},
    {'kec': 'Talango', 'desa': 'Gowa-Gowa'},

    // 4. Saronggi
    {'kec': 'Saronggi', 'desa': 'Saronggi'},
    {'kec': 'Saronggi', 'desa': 'Tanah Merah'},
    {'kec': 'Saronggi', 'desa': 'Juluk'},
    {'kec': 'Saronggi', 'desa': 'Nambakor'},
    {'kec': 'Saronggi', 'desa': 'Langsar'},
    {'kec': 'Saronggi', 'desa': 'Kebundadap Timur'},
    {'kec': 'Saronggi', 'desa': 'Kebundadap Barat'},
    {'kec': 'Saronggi', 'desa': 'Pagarbatu'},
    {'kec': 'Saronggi', 'desa': 'Tanjung'},
    {'kec': 'Saronggi', 'desa': 'Moangan'},

    // 5. Bluto
    {'kec': 'Bluto', 'desa': 'Bluto'},
    {'kec': 'Bluto', 'desa': 'Aengbaja Raja'},
    {'kec': 'Bluto', 'desa': 'Aengbaja Kenek'},
    {'kec': 'Bluto', 'desa': 'Pakandangan Barat'},
    {'kec': 'Bluto', 'desa': 'Pakandangan Tengah'},
    {'kec': 'Bluto', 'desa': 'Pakandangan Sangra'},
    {'kec': 'Bluto', 'desa': 'Sera Barat'},
    {'kec': 'Bluto', 'desa': 'Sera Timur'},
    {'kec': 'Bluto', 'desa': 'Karang Cempaka'},
    {'kec': 'Bluto', 'desa': 'Lobuk'},
    {'kec': 'Bluto', 'desa': 'Gulukmanjung'},

    // 6. Lenteng
    {'kec': 'Lenteng', 'desa': 'Lenteng Timur'},
    {'kec': 'Lenteng', 'desa': 'Lenteng Barat'},
    {'kec': 'Lenteng', 'desa': 'Ellak Laok'},
    {'kec': 'Lenteng', 'desa': 'Ellak Daya'},
    {'kec': 'Lenteng', 'desa': 'Taraban'},
    {'kec': 'Lenteng', 'desa': 'Banaresep Timur'},
    {'kec': 'Lenteng', 'desa': 'Banaresep Barat'},
    {'kec': 'Lenteng', 'desa': 'Poreh'},
    {'kec': 'Lenteng', 'desa': 'Cangkreng'},
    {'kec': 'Lenteng', 'desa': 'Meddelan'},
    {'kec': 'Lenteng', 'desa': 'Sendir'},

    // 7. Gapura
    {'kec': 'Gapura', 'desa': 'Gapura Barat'},
    {'kec': 'Gapura', 'desa': 'Gapura Timur'},
    {'kec': 'Gapura', 'desa': 'Gapura Tengah'},
    {'kec': 'Gapura', 'desa': 'Andulang'},
    {'kec': 'Gapura', 'desa': 'Balo'},
    {'kec': 'Gapura', 'desa': 'Banjar Barat'},
    {'kec': 'Gapura', 'desa': 'Banjar Timur'},
    {'kec': 'Gapura', 'desa': 'Batudinding'},
    {'kec': 'Gapura', 'desa': 'Beraji'},
    {'kec': 'Gapura', 'desa': 'Braji'},
    {'kec': 'Gapura', 'desa': 'Karangbudi'},
    {'kec': 'Gapura', 'desa': 'Longos'},
    {'kec': 'Gapura', 'desa': 'Mandala'},
    {'kec': 'Gapura', 'desa': 'Paloloan'},
    {'kec': 'Gapura', 'desa': 'Panagan'},
    {'kec': 'Gapura', 'desa': 'Poja'},

    // 8. Batang-Batang
    {'kec': 'Batang-Batang', 'desa': 'Batang-Batang Laok'},
    {'kec': 'Batang-Batang', 'desa': 'Batang-Batang Daya'},
    {'kec': 'Batang-Batang', 'desa': 'Banuaju Barat'},
    {'kec': 'Batang-Batang', 'desa': 'Banuaju Timur'},
    {'kec': 'Batang-Batang', 'desa': 'Bilangan'},
    {'kec': 'Batang-Batang', 'desa': 'Dapenda'},
    {'kec': 'Batang-Batang', 'desa': 'Jangkong'},
    {'kec': 'Batang-Batang', 'desa': 'Jenang'},
    {'kec': 'Batang-Batang', 'desa': 'Kolpo'},
    {'kec': 'Batang-Batang', 'desa': 'Legung Barat'},
    {'kec': 'Batang-Batang', 'desa': 'Legung Timur'},
    {'kec': 'Batang-Batang', 'desa': 'Lombang'},
    {'kec': 'Batang-Batang', 'desa': 'Nyabakan Barat'},
    {'kec': 'Batang-Batang', 'desa': 'Nyabakan Timur'},
    {'kec': 'Batang-Batang', 'desa': 'Tamedung'},

    // 9. Dungkek
    {'kec': 'Dungkek', 'desa': 'Dungkek'},
    {'kec': 'Dungkek', 'desa': 'Bicabi'},
    {'kec': 'Dungkek', 'desa': 'Bungin-Bungin'},
    {'kec': 'Dungkek', 'desa': 'Candi'},
    {'kec': 'Dungkek', 'desa': 'Ginih'},
    {'kec': 'Dungkek', 'desa': 'Jadung'},
    {'kec': 'Dungkek', 'desa': 'Lapa Daya'},
    {'kec': 'Dungkek', 'desa': 'Lapa Laok'},
    {'kec': 'Dungkek', 'desa': 'Lapa Taman'},
    {'kec': 'Dungkek', 'desa': 'Romben Barat'},
    {'kec': 'Dungkek', 'desa': 'Romben Guna'},
    {'kec': 'Dungkek', 'desa': 'Romben Rana'},
    {'kec': 'Dungkek', 'desa': 'Taman Sare'},

    // 10. Rubaru
    {'kec': 'Rubaru', 'desa': 'Rubaru'},
    {'kec': 'Rubaru', 'desa': 'Banasare'},
    {'kec': 'Rubaru', 'desa': 'Basoka'},
    {'kec': 'Rubaru', 'desa': 'Bunbarat'},
    {'kec': 'Rubaru', 'desa': 'Duko'},
    {'kec': 'Rubaru', 'desa': 'Kalebengan'},
    {'kec': 'Rubaru', 'desa': 'Karangnangka'},
    {'kec': 'Rubaru', 'desa': 'Mandala'},
    {'kec': 'Rubaru', 'desa': 'Matanair'},
    {'kec': 'Rubaru', 'desa': 'Pakondang'},
    {'kec': 'Rubaru', 'desa': 'Tambaksari'},

    // 11. Ambunten
    {'kec': 'Ambunten', 'desa': 'Ambunten Timur'},
    {'kec': 'Ambunten', 'desa': 'Ambunten Barat'},
    {'kec': 'Ambunten', 'desa': 'Ambunten Tengah'},
    {'kec': 'Ambunten', 'desa': 'Belluk Ares'},
    {'kec': 'Ambunten', 'desa': 'Belluk Raja'},
    {'kec': 'Ambunten', 'desa': 'Campor Barat'},
    {'kec': 'Ambunten', 'desa': 'Campor Timur'},
    {'kec': 'Ambunten', 'desa': 'Tambaagung Ares'},
    {'kec': 'Ambunten', 'desa': 'Tambaagung Barat'},
    {'kec': 'Ambunten', 'desa': 'Tambaagung Timur'},
    {'kec': 'Ambunten', 'desa': 'Tambaagung Tengah'},
    {'kec': 'Ambunten', 'desa': 'Keles'},
    {'kec': 'Ambunten', 'desa': 'Sogian'},

    // 12. Pasongsongan
    {'kec': 'Pasongsongan', 'desa': 'Pasongsongan'},
    {'kec': 'Pasongsongan', 'desa': 'Panaongan'},
    {'kec': 'Pasongsongan', 'desa': 'Padangdangan'},
    {'kec': 'Pasongsongan', 'desa': 'Montorna'},
    {'kec': 'Pasongsongan', 'desa': 'Campaka'},
    {'kec': 'Pasongsongan', 'desa': 'Rajun'},
    {'kec': 'Pasongsongan', 'desa': 'Soddara'},
    {'kec': 'Pasongsongan', 'desa': 'Lebeng Barat'},
    {'kec': 'Pasongsongan', 'desa': 'Lebeng Timur'},

    // 13. Guluk-Guluk
    {'kec': 'Guluk-Guluk', 'desa': 'Guluk-Guluk'},
    {'kec': 'Guluk-Guluk', 'desa': 'Payudan Dundang'},
    {'kec': 'Guluk-Guluk', 'desa': 'Payudan Karangsokon'},
    {'kec': 'Guluk-Guluk', 'desa': 'Payudan Nangger'},
    {'kec': 'Guluk-Guluk', 'desa': 'Bragung'},
    {'kec': 'Guluk-Guluk', 'desa': 'Batuampar'},
    {'kec': 'Guluk-Guluk', 'desa': 'Pordapor'},
    {'kec': 'Guluk-Guluk', 'desa': 'Bakeong'},
    {'kec': 'Guluk-Guluk', 'desa': 'Pananggungan'},

    // 14. Ganding
    {'kec': 'Ganding', 'desa': 'Ganding'},
    {'kec': 'Ganding', 'desa': 'Ketawang Larangan'},
    {'kec': 'Ganding', 'desa': 'Ketawang Karay'},
    {'kec': 'Ganding', 'desa': 'Ketawang Parebaan'},
    {'kec': 'Ganding', 'desa': 'Rombiya Barat'},
    {'kec': 'Ganding', 'desa': 'Rombiya Timur'},
    {'kec': 'Ganding', 'desa': 'Bataal Barat'},
    {'kec': 'Ganding', 'desa': 'Bataal Timur'},
    {'kec': 'Ganding', 'desa': 'Talaga'},

    // 15. Pragaan
    {'kec': 'Pragaan', 'desa': 'Pragaan Laok'},
    {'kec': 'Pragaan', 'desa': 'Pragaan Daya'},
    {'kec': 'Pragaan', 'desa': 'Karduluk'},
    {'kec': 'Pragaan', 'desa': 'Pakamban Laok'},
    {'kec': 'Pragaan', 'desa': 'Pakamban Daya'},
    {'kec': 'Pragaan', 'desa': 'Sendang'},
    {'kec': 'Pragaan', 'desa': 'Jaddung'},
    {'kec': 'Pragaan', 'desa': 'Aeng Panas'},
    {'kec': 'Pragaan', 'desa': 'Larangan Perreng'},
    {'kec': 'Pragaan', 'desa': 'Kaduara Timur'},

    // 16. Manding
    {'kec': 'Manding', 'desa': 'Manding Laok'},
    {'kec': 'Manding', 'desa': 'Manding Daya'},
    {'kec': 'Manding', 'desa': 'Manding Timur'},
    {'kec': 'Manding', 'desa': 'Gadding'},
    {'kec': 'Manding', 'desa': 'Gunung Kembar'},
    {'kec': 'Manding', 'desa': 'Jaba\'an'},
    {'kec': 'Manding', 'desa': 'Kasengan'},
    {'kec': 'Manding', 'desa': 'Lanjuk'},
    {'kec': 'Manding', 'desa': 'Tenonan'},

    // 17. Dasuk
    {'kec': 'Dasuk', 'desa': 'Dasuk Laok'},
    {'kec': 'Dasuk', 'desa': 'Dasuk Barat'},
    {'kec': 'Dasuk', 'desa': 'Dasuk Timur'},
    {'kec': 'Dasuk', 'desa': 'Bringin'},
    {'kec': 'Dasuk', 'desa': 'Jelbudan'},
    {'kec': 'Dasuk', 'desa': 'Kecer'},
    {'kec': 'Dasuk', 'desa': 'Kerta Barat'},
    {'kec': 'Dasuk', 'desa': 'Kerta Timur'},
    {'kec': 'Dasuk', 'desa': 'Nyapar'},
    {'kec': 'Dasuk', 'desa': 'Semaan'},
    {'kec': 'Dasuk', 'desa': 'Slopeng'},

    // 18. Batuputih
    {'kec': 'Batuputih', 'desa': 'Batuputih Laok'},
    {'kec': 'Batuputih', 'desa': 'Batuputih Daya'},
    {'kec': 'Batuputih', 'desa': 'Batuputih Kenek'},
    {'kec': 'Batuputih', 'desa': 'Badur'},
    {'kec': 'Batuputih', 'desa': 'Bantelan'},
    {'kec': 'Batuputih', 'desa': 'Bulla\'an'},
    {'kec': 'Batuputih', 'desa': 'Juruan Daya'},
    {'kec': 'Batuputih', 'desa': 'Juruan Laok'},
    {'kec': 'Batuputih', 'desa': 'Larangan Barma'},
    {'kec': 'Batuputih', 'desa': 'Larangan Kerta'},
    {'kec': 'Batuputih', 'desa': 'Sergang'},
    {'kec': 'Batuputih', 'desa': 'Tengedan'},

    // 19. Batuan
    {'kec': 'Batuan', 'desa': 'Batuan'},
    {'kec': 'Batuan', 'desa': 'Babbalan'},
    {'kec': 'Batuan', 'desa': 'Gedungan'},
    {'kec': 'Batuan', 'desa': 'Gelugur'},
    {'kec': 'Batuan', 'desa': 'Gunggung'},
    {'kec': 'Batuan', 'desa': 'Patean'},
    {'kec': 'Batuan', 'desa': 'Torbang'},

    // 20. Arjasa (Kepulauan Kangean)
    {'kec': 'Arjasa (Kangean)', 'desa': 'Arjasa'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Angkatan'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Bilis-Bilis'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Buddi'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Duko'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Kalikatak'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Kalinganyar'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Kalisangka'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Kolo-Kolo'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Laok Jang-Jang'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Pabian'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Pajanangger'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Pandeman'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Paseraman'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Sambakati'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Sawah Sumur'},
    {'kec': 'Arjasa (Kangean)', 'desa': 'Sumber Nangka'},

    // 21. Kangayan (Kepulauan Kangean)
    {'kec': 'Kangayan (Kangean)', 'desa': 'Kangayan'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Batuputih'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Cangkramaan'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Daandung'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Jikakenek'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Saobi'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Tamberu'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Timur Jang-Jang'},
    {'kec': 'Kangayan (Kangean)', 'desa': 'Torjek'},

    // 22. Sapeken (Kepulauan Sapeken)
    {'kec': 'Sapeken', 'desa': 'Sapeken'},
    {'kec': 'Sapeken', 'desa': 'Pagerungan Besar'},
    {'kec': 'Sapeken', 'desa': 'Pagerungan Kecil'},
    {'kec': 'Sapeken', 'desa': 'Paliat'},
    {'kec': 'Sapeken', 'desa': 'Sabuntan'},
    {'kec': 'Sapeken', 'desa': 'Sadulang'},
    {'kec': 'Sapeken', 'desa': 'Sakala'},
    {'kec': 'Sapeken', 'desa': 'Saur Saebus'},
    {'kec': 'Sapeken', 'desa': 'Sepanjang'},
    {'kec': 'Sapeken', 'desa': 'Tanjung Kiaok'},

    // 23. Nonggunong (Kepulauan Sapudi)
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Nonggunong'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Rosong'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Sokarame Pesisir'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Sokarame Timur'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Sonok'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Talaga'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Tarebung'},
    {'kec': 'Nonggunong (Sapudi)', 'desa': 'Tanah Merah'},

    // 24. Gayam (Kepulauan Sapudi)
    {'kec': 'Gayam (Sapudi)', 'desa': 'Gayam'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Gendang Barat'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Gendang Timur'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Jambuir'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Kalowang'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Karang Tengah'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Karyaki'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Nyamplong'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Pancor'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Prambanan'},
    {'kec': 'Gayam (Sapudi)', 'desa': 'Tarebung'},

    // 25. Raas (Kepulauan Raas)
    {'kec': 'Raas', 'desa': 'Alasmalang'},
    {'kec': 'Raas', 'desa': 'Berakit'},
    {'kec': 'Raas', 'desa': 'Brakas'},
    {'kec': 'Raas', 'desa': 'Guwa-Guwa'},
    {'kec': 'Raas', 'desa': 'Jungkat'},
    {'kec': 'Raas', 'desa': 'Karangnangka'},
    {'kec': 'Raas', 'desa': 'Ketupat'},
    {'kec': 'Raas', 'desa': 'Kropoh'},
    {'kec': 'Raas', 'desa': 'Poteran'},
    {'kec': 'Raas', 'desa': 'Tonduk'},

    // 26. Masalembu (Kepulauan Masalembu)
    {'kec': 'Masalembu', 'desa': 'Sukajeruk'},
    {'kec': 'Masalembu', 'desa': 'Masalima'},
    {'kec': 'Masalembu', 'desa': 'Masakambing'},
    {'kec': 'Masalembu', 'desa': 'Karamian'},

    // 27. Giligenting (Kepulauan Giligenting)
    {'kec': 'Giligenting', 'desa': 'Aeng Anyar'},
    {'kec': 'Giligenting', 'desa': 'Banbaru'},
    {'kec': 'Giligenting', 'desa': 'Banmaleng'},
    {'kec': 'Giligenting', 'desa': 'Bringsang'},
    {'kec': 'Giligenting', 'desa': 'Galis'},
    {'kec': 'Giligenting', 'desa': 'Gedugan'},
    {'kec': 'Giligenting', 'desa': 'Jombag'},
    {'kec': 'Giligenting', 'desa': 'Lombang'},
  ];
}
